### ISSUE TITLE
the `@line` in generated XMIR doesn't provide valuable data

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#848]
I see this:

```xml
<o base="org.eolang.jeo.opcode" line="1696557278" name="aload-14">
  <o base="org.eolang.jeo.int">
    <o base="bytes" data="bytes">00 00 00 00 00 00 00 19</o>
  </o>
  <o base="org.eolang.jeo.int">
    <o base="bytes" data="bytes">00 00 00 00 00 00 00 00</o>
  </o>
</o>
```

The value `1696557278` doesn't make any sense (I believe, it's `System.nanoTime()` or a random). Instead, let's put there the number of the byte in the `.class` file, where the `opcode` was found (the position of it, starting from zero).

**Comment by yegor256** [comment]
@volodya-lombrozo please, check

**Comment by volodya-lombrozo** [comment]
@yegor256 I strongly believe, that `line` attribute should be removed from `xmir` and from `jeo`: https://github.com/objectionary/jeo-maven-plugin/issues/635

So, it's better to fix the original problem. What do you think?

**Comment by yegor256** [comment]
@volodya-lombrozo I'm not sure it's technically possible. Imagine, this code:

```
[] > foo

[] > bar
  [] > foo
  foo > x
```

Java alternative to this would be:

```
class Foo {}
class Bar {
  class Foo {}
  private Foo x;
}
```

Then, you map it to XMIR:

```
<o name="foo" />
<o name="bar">
  <o name="foo" />
  <o name="x" base="foo"/> <!-- here! --> 
</o>
```

The question is: what `foo` is meant there? Somehow we must give compiler a clue, which `foo` we refer to, since there are two `foo` objects visible in this file. Currently, we do it like this:

```
<o name="foo" />
<o name="bar">
  <o name="foo" line="999" />
  <o name="x" base="foo" ref="999"/>
</o>
```

We can replace `ref`/`line` pair with something else, but it's still going to be a pair of attributes.

**Comment by volodya-lombrozo** [comment]
@yegor256 it might be a single attribute `id`

**Comment by volodya-lombrozo** [comment]
@yegor256 The `line` attribute is related to the source code only. Any IR shouldn't know about source code details, except as optional elements (e.g., debug info).

**Comment by yegor256** [comment]
@volodya-lombrozo indeed, we can call it `id`+`ref`, but we still have the same pair of attributes. You just don't like the name `line`?

**Comment by volodya-lombrozo** [comment]
@yegor256 It's not just a name. The `line` attribute currently serves two purposes:

1. It acts as a unique identifier for objects, allowing us to differentiate one object from another.
2. It provides debugging information, helping us "locate" an object in the source code.

Both purposes are important, but (1) is mandatory, whereas (2) is optional. However, since these two purposes are combined now, (2) has effectively become mandatory as well. This is extremely misleading: mandatory debug information in IR.

I believe we should:

1. Keep the `line` attribute but make it optional (similar to how Java `bytecode` handles it, for example).
2. Create a separate `id` attribute and make it mandatory.
___
P.S.
From an architectural point of view, the `line` attribute is a clear violation of the Single Responsibility Principle ([SRP](https://en.wikipedia.org/wiki/Single-responsibility_principle))
